### ISSUE TITLE
libatomic.so.1: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by ghimiredhikura** [OAID/Tengine-Convert-Tools#26]
# Target
Device: Raspberrypi3b+
OS: Raspberry Pi OS (32 bit)

# build error: 
```ruby
/usr/bin/ld: ../libtengine-serializer.a(graph_task.cpp.o): undefined reference to symbol '__atomic_fetch_sub_8@@LIBATOMIC_1.0'
/usr/bin/ld: //usr/lib/arm-linux-gnueabihf/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tools/CMakeFiles/tm_convert_tool.dir/build.make:512: tools/tm_convert_tool] Error 1
make[1]: *** [CMakeFiles/Makefile2:195: tools/CMakeFiles/tm_convert_tool.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Any idea please how to solve this issue?

**Comment by BUG1989** [comment]
This tool can only compile on Linux-x86（maybe Ubuntu 18.04）, Please try it again.

**Comment by kalcohol** [comment]
Hi Deepak Ghimire, convert tools was only fully tested in x86 linux for now, we do not have enough developers to support arm devices this year. So could u try to build this via x86 linux?
